### ISSUE TITLE
Do auxiliary distributions are used to predict outcome?

### ISSUE THREAD

**Issue by WeilinChen507** [WeijiaZhang24/TEDVAE#1]
### description:

**Hello, I am using the codes of TEDVAE. In the paper, it points out that the predicted outcomes y are inferred using the auxiliary classifier in the inference model (the auxiliary distributions in the Guide part in codes), but the predicted outcomes y seems to be inferred from the generative model (the outcome from the Model part in codes). Could u tell me which distribution (in Guide or in Model?) are used to inferred y? Thanks very much.**

**Comment by WeijiaZhang24** [comment]
It should be the generative model.

**Comment by WeilinChen507** [comment]
> It should be the generative model.

Thanks very much.
