### ISSUE TITLE
Can't reproduce the results

### ISSUE THREAD

**Issue by mbuchwa** [WeijiaZhang24/TEDVAE#2]
I am training the TEDVAE on my RTX A5000. As far as mentioned in the paper, 
I am using the same configuration of hyperparameters.

![Screenshot from 2021-11-22 14-47-43](https://user-images.githubusercontent.com/58557930/142872854-78aeea31-c139-4907-9ed1-5f2653d9296e.png)

However, the model only achieves a PEHE_test for IHDP_b of **2.170 +- 0.298** !

Can someone reproduce the paper results and tell me what I am missing? 
Thanks in advance!

**Comment by WeijiaZhang24** [comment]
I think the reported PEHE_test for IHDP_b was 2.2, so 2.170 seems reasonable.
